# - Try to find the MusicBrainz library
# Once done this will define
#
#  MUSICBRAINZ_FOUND       - system has MusicBrainz
#  MUSICBRAINZ_INCLUDE_DIR - the MusicBrainz include directory
#  MUSICBRAINZ_LIBRARIES   - Link these to use MusicBrainz
#

if (MUSICBRAINZ_INCLUDE_DIR AND MUSICBRAINZ_LIBRARIES)
  # in cache already
  SET(MUSICBRAINZ_FOUND TRUE)

else (MUSICBRAINZ_INCLUDE_DIR AND MUSICBRAINZ_LIBRARIES)

  FIND_PATH(MUSICBRAINZ_INCLUDE_DIR musicbrainz5/mb5_c.h)

  FIND_LIBRARY(MUSICBRAINZ_LIBRARY musicbrainz5cc)

  IF (MUSICBRAINZ_LIBRARY)
    SET(MUSICBRAINZ_LIBRARIES ${MUSICBRAINZ_LIBRARY} "-lm")
  ENDIF (MUSICBRAINZ_LIBRARY)

  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(MusicBrainz DEFAULT_MSG
                                    MUSICBRAINZ_LIBRARIES MUSICBRAINZ_INCLUDE_DIR)

  MARK_AS_ADVANCED(MUSICBRAINZ_INCLUDE_DIR MUSICBRAINZ_LIBRARIES)

endif (MUSICBRAINZ_INCLUDE_DIR AND MUSICBRAINZ_LIBRARIES)
