# - Try to find the CoverArt library
# Once done this will define
#
#  COVERART_FOUND       - system has CoverArt
#  COVERART_INCLUDE_DIR - the CoverArt include directory
#  COVERART_LIBRARIES   - Link these to use CoverArt
#

if (COVERART_INCLUDE_DIR AND COVERART_LIBRARIES)
  # in cache already
  SET(COVERART_FOUND TRUE)

else (COVERART_INCLUDE_DIR AND COVERART_LIBRARIES)

  FIND_PATH(COVERART_INCLUDE_DIR coverart/caa_c.h)

  FIND_LIBRARY(COVERART_LIBRARY coverartcc)

  IF (COVERART_LIBRARY)
    SET(COVERART_LIBRARIES ${COVERART_LIBRARY} "-lm")
  ENDIF (COVERART_LIBRARY)

  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(CoverArt DEFAULT_MSG
                                    COVERART_LIBRARIES COVERART_INCLUDE_DIR)

  MARK_AS_ADVANCED(COVERART_INCLUDE_DIR COVERART_LIBRARIES)

endif (COVERART_INCLUDE_DIR AND COVERART_LIBRARIES)
